tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "universal-ctags/universal-ctags"

brew "asdf"
brew "bat"
brew "colordiff"
brew "coreutils"
brew "diff-so-fancy"
brew "direnv"
brew "fzf"
brew "gpg"
brew "htop"
brew "nvim", args: ["HEAD"]
brew "reattach-to-user-namespace"
brew "starship"
brew "the_silver_searcher"
brew "thefuck"
brew "tmux"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew "watch"
brew "zsh"

cask "alacritty"
cask "authy"
cask "docker"
cask "font-fira-code-nerd-font"
cask "google-chrome"
cask "insomnia"
cask "iterm2"
cask "maccy"
cask "pritunl"
cask "shiftit"
cask "slack"
