#!/usr/bin/env bash

pushd ~
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install stow

rm -fr ~/.dotfiles
git clone https://github.com/danielgatis/dotfiles.git .dotfiles

pushd .dotfiles
stow -v -R -t ~ home
popd

brew bundle --global --force --no-lock || true
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

tmux start-server
tmux new-session -d
sh ~/.tmux/plugins/tpm/scripts/install_plugins.sh
tmux kill-server

popd
