#!/usr/bin/env bash

# Might as well ask for password up-front, right?
sudo -v

# https for git
git config --global url."https://github.com/".insteadOf git@github.com:
git config --global url."https://".insteadOf git://

# Keep-alive: update existing sudo time stamp if set, otherwise do nothing.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# checkout
rm -fr $HOME/.dotfiles
git clone "https://github.com/danielgatis/dotfiles.git" "$HOME/.dotfiles"

# install homewbrew and bundle
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
cd $HOME/.dotfiles
brew bundle --force
cd $HOME

# copy dotfiles to home
declare -a FILES_TO_SYMLINK=$(find $HOME/.dotfiles -type f -maxdepth 1 -name ".*" -not -name init.lua -not -name .DS_Store -not -name .git -exec basename {} \;)

for i in ${FILES_TO_SYMLINK[@]}; do
  sourceFile="$HOME/.dotfiles/$i"
  targetFile="$HOME/$(printf "%s" "$i" | sed "s/.*\/\(.*\)/\1/g")"
  ln -fs $sourceFile $targetFile
  echo "${sourceFile} → ${targetFile}"
done

# copy init.lua
mkdir -p ~/.config/nvim
ln -fs ~/.dotfiles/init.lua ~/.config/nvim/init.lua
echo "~/.dotfiles/init.lua → ~/.config/nvim/init.lua"

# set zsh as default shell
sudo sh -c "echo $(which zsh) >> /etc/shells"
chsh -s $(which zsh)
zsh
source ~/.zshrc

# revert git to default
git config --global --unset-all url.https://github.com/.insteadof
git config --global --unset-all url.https://.insteadof
