live_config_reload: true

env:
  ZSH_TMUX_AUTOSTART: "true"
  TERM: "xterm-256color"

window:
  decorations: Buttonless
  padding:
    x: 10
    y: 10

scrolling:
  history: 99999

mouse:
  selection:
    save_to_clipboard: true

font:
  size: 16
  normal:
    family: FiraCode Nerd Font

key_bindings:
  - { key: N,          mods: Command,          action: CreateNewWindow                       }
  - { key: Q,          mods: Command,          action: Quit                                  }
  - { key: W,          mods: Command,          action: Quit                                  }
  - { key: Left,       mods: Shift,            chars: "\x1b[1;2D"                            }
  - { key: Left,       mods: Control,          chars: "\x1b[1;5D"                            }
  - { key: Left,       mods: Alt,              chars: "\x1b[1;3D"                            }
  - { key: Left,                               chars: "\x1b[D",            mode: ~AppCursor  }
  - { key: Left,                               chars: "\x1bOD",            mode: AppCursor   }
  - { key: Right,      mods: Shift,            chars: "\x1b[1;2C"                            }
  - { key: Right,      mods: Control,          chars: "\x1b[1;5C"                            }
  - { key: Right,      mods: Alt,              chars: "\x1b[1;3C"                            }
  - { key: Right,                              chars: "\x1b[C",            mode: ~AppCursor  }
  - { key: Right,                              chars: "\x1bOC",            mode: AppCursor   }
  - { key: Up,         mods: Shift,            chars: "\x1b[1;2A"                            }
  - { key: Up,         mods: Control,          chars: "\x1b[1;5A"                            }
  - { key: Up,         mods: Alt,              chars: "\x1b[1;3A"                            }
  - { key: Up,                                 chars: "\x1b[A",            mode: ~AppCursor  }
  - { key: Up,                                 chars: "\x1bOA",            mode: AppCursor   }
  - { key: Down,       mods: Shift,            chars: "\x1b[1;2B"                            }
  - { key: Down,       mods: Control,          chars: "\x1b[1;5B"                            }
  - { key: Down,       mods: Alt,              chars: "\x1b[1;3B"                            }
  - { key: Down,                               chars: "\x1b[B",            mode: ~AppCursor  }
  - { key: Down,                               chars: "\x1bOB",            mode: AppCursor   }
  - { key: Space,      mods: Control,          chars: "\x00"                                 } # Ctrl + Space
  - { key: Grave,      mods: Alt,              chars: "\x1b`"                                } # Alt + `
  - { key: Grave,      mods: Alt|Shift,        chars: "\x1b~"                                } # Alt + ~
  - { key: Period,     mods: Alt,              chars: "\x1b."                                } # Alt + .
  - { key: Period,     mods: Alt|Shift,        chars: "\x1b>"                                } # Alt + >
  - { key: Comma,      mods: Alt|Shift,        chars: "\x1b<"                                } # Alt + <
  - { key: Minus,      mods: Alt|Shift,        chars: "\x1b_"                                } # Alt + _
  - { key: Backslash,  mods: Alt,              chars: "\x1b\\"                               } # Alt + \
  - { key: Backslash,  mods: Alt|Shift,        chars: "\x1b|"                                } # Alt + |
  - { key: Slash,      mods: Alt,              chars: "\x1b/"                                } # Alt + /
  - { key: RBracket,   mods: Alt,              chars: "\x1b]"                                } # Alt + ]
  - { key: LBracket,   mods: Alt,              chars: "\x1b["                                } # Alt + [

# TokyoNight Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x1a1b26'
    foreground: '0xc0caf5'

  # Normal colors
  normal:
    black:   '0x15161E'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xa9b1d6'

  # Bright colors
  bright:
    black:   '0x414868'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xc0caf5'

  indexed_colors:
    - { index: 16, color: '0xff9e64' }
    - { index: 17, color: '0xdb4b4b' }
