tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

brew "asciinema"
brew "bat"
brew "colordiff"
brew "coreutils"
brew "difftastic"
brew "direnv"
brew "fzf"
brew "gpg"
brew "htop"
brew "nvim"
brew "starship"
brew "the_silver_searcher"
brew "thefuck"
brew "watch"
brew "zplug"
brew "zsh"

cask_args require_sha: true, force: true

cask "alacritty"
cask "amethyst"
cask "authy"
cask "docker"
cask "font-fira-code-nerd-font"
cask "google-chrome"
cask "insomnia"
cask "intellij-idea"
cask "iterm2"
cask "maccy"
cask "slack"
cask "visual-studio-code"
cask "hammerspoon"
