tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

brew "asciinema"
brew "asdf"
brew "bat"
brew "coreutils"
brew "diff-so-fancy"
brew "direnv"
brew "fd"
brew "fzf"
brew "gpg"
brew "htop"
brew "nvim"
brew "rectangle"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tree"
brew "watch"
brew "zplug"
brew "zsh"

cask_args require_sha: true, force: true

cask "alacritty"
cask "authy"
cask "cakebrew"
cask "docker"
cask "font-fira-code-nerd-font"
cask "google-chrome"
cask "insomnia"
cask "intellij-idea"
cask "keycastr"
cask "sourcetree"
cask "spotify"
cask "visual-studio-code"
